### ISSUE TITLE
Invalid value for column collection_id in table bsos: Expected INT64.

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#1055] opened 2021-04-28 18:08 UTC
Per sentry:

https://sentry.prod.mozaws.net/operations/syncstorage-dev/issues/11102490/?environment=release

`
A database error occurred: RpcFailure: 9-FAILED_PRECONDITION Invalid value for column collection_id in table bsos: Expected INT64.
`

This began 9 days ago, so it's very likely related to the #1046 refactor.

**Comment by ethowitz** [comment] 2021-04-28 19:03
I was able to reproduce this locally. Still new to Protobuf and Spanner, but here's what I think is happening. `collection_id` is an `INT64` in the Spanner schema, and if we convert it to a string in the protobuf (which we were doing before), Spanner can convert that string into an `INT64`. When I wrote the new trait, I converted the `collection_id` (an `i32`) to a protobuf [`Value`](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Value) using the [`set_number_value()`](https://docs.rs/protobuf/2.22.1/protobuf/well_known_types/struct.Value.html#method.set_number_value), function, which converts the number to a floating point. I'm guessing that when you try to insert a floating point number into an `INT64` column, Spanner assumes you made an error instead of trying to convert it implicitly to an `INT64`.

This could be resolved by going back to converting the `collection_id` (and the `sortindex` and `ttl`) to a string prior to sending it to the database or by constructing the static `Int64Value` protobuf types.

**Comment by jrconlin** [comment] 2021-04-28 19:54
Part of the problem is that there are a lot of systems that are trying to be "helpful". There's rust, which does strong typing. There's protobuf, which also does strong typing, but differently. There's Javascript, which is one of the transport layers, which is not strongly typed, and quite less helpful,...

At this point, using declared type and string formatting is probably the safest thing.

**Comment by ethowitz** [comment] 2021-04-28 19:58
In the PR I opened, I reverted to converting integers to strings before converting to protobuf values for expediency. I think making the switch to the static protobuf values will require more investigative work (and more substantial changes), so I figured it would be best to get a quick fix into master first. That said, if we think it's worth making the switch over to the static types now, I'm happy to do it 👍

**Closed** 2021-04-30 16:09 UTC
Labels: bug
