### ISSUE TITLE
Test against spanner in circle

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/syncstorage-rs#456] opened 2020-02-28 19:27 UTC
Right now, we run the db-tests against mysql in circle. But, the code between mysql and spanner has diverged quite a bit, and we really need to also test against spanner in circle in order to get good coverage.

**Comment by pjenvey** [comment] 2020-02-28 19:33
dupe of #167

**Closed by pjenvey** 2020-02-28 19:33 UTC
