### ISSUE TITLE
Write functional tests that cover the tokenserver functionality, or modernize the old tokenserver load tester and use that

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/syncstorage-rs#868] opened 2020-10-19 23:05 UTC
There's some very old load testing code for the tokenserver that could be modernized to get functional test coverage. We should either modernize it or copy the same tests into something modern.

**Comment by ethowitz** [comment] 2021-06-01 20:47
Duplicate of #1048

**Closed by ethowitz** 2021-06-01 20:47 UTC
Labels: 8, tokenserver
