### ISSUE TITLE
Clean up default config settings

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/syncstorage-rs#1250] opened 2022-03-15 16:25 UTC
With [this change](https://github.com/mehcode/config-rs/issues/60) to config-rs, a bug has been fixed that was preventing us from using the `Default` implementation for the `Settings` struct. We can remove most or all of the calls to `set_default` in `Settings::with_env_and_config_file` in favor of the defaults set in the `Default` implementation.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1700)

**Comment by ethowitz** [comment] 2022-03-15 16:29
Duplicate of #253

**Closed by ethowitz** 2022-03-15 16:29 UTC

**Comment by data-sync-user** [comment] 2022-05-17 21:14
➤ Ethan Donowitz commented:

This will be done as part of CONSVC-1744
