### ISSUE TITLE
Lockwise sync hangs after deleting an item

### ISSUE THREAD

**Issue by rfk** [mozilla-services/syncstorage-rs#375] opened 2019-12-12 23:29 UTC
I only noticed this after using the durable sync server, so I'm tentatively filing it as durable-sync-specific. If we are able to repro this on the existing sync infra then it may be a client bug.

STR:

* Connect desktop and Lockwise for Android to the same account.
* Add a new login on desktop. Sync Lockwise, and observe that the new login appears.
* Delete the new login in Lockwise. Attempt to Sync Lockwise.

Expected result:

* The login record deletion is synced back up to desktop

Actual result:

* Lockwise shows the "syncing your logins..." spinner and seems to hand indefinitely.
* The login record deletion does not get synced back up to desktop

After killing the lockwise app, it now refuses to start up for me, getting stuck on the initial "Firefox Lockwise" splash screen.

**Comment by rfk** [comment] 2019-12-12 23:39
> After killing the lockwise app, it now refuses to start up for me, getting stuck on the initial "Firefox Lockwise" splash screen.

It eventually got past this screen, but is now silently failing to unlock via fingerprint.

**Comment by rfk** [comment] 2019-12-13 05:39
I captured some logs and I think this is the same underlying error as #376:

```
12-13 16:35:57.891  3764  3794 I sync15::client: Request "/1.5/131779961/storage/passwords" has incoming x-last-modified ServerTimestamp(1576215359560)
12-13 16:35:57.892  3764  3794 D sync15::request: Committed batch NoBatch
12-13 16:35:57.892  3764  3794 W sync15::sync_multiple: Sync of passwords failed! Error(
12-13 16:35:57.892  3764  3794 W sync15::sync_multiple:
12-13 16:35:57.892  3764  3794 W sync15::sync_multiple: Not all records were successfully uploaded)
12-13 16:35:57.893  3764  3794 I sync15::sync_multiple: Finished syncing stores. All successful: false
12-13 16:35:57.894  3764  3794 I sync15::sync_multiple: Updating persisted global state
12-13 16:35:57.894  3764  3794 D sync15::sync_multiple: sync was successful, final status=Ok
12-13 16:35:57.936  3764  3794 E logins::ffi: Sync error Error(
12-13 16:35:57.936  3764  3794 E logins::ffi:
12-13 16:35:57.936  3764  3794 E logins::ffi: Not all records were successfully uploaded)
```

Still working on a debug build for Fenix to dig in further.

**Comment by rfk** [comment] 2019-12-13 23:23
(I think there is probably *also* a lockwise bug in here about better handlig of failed syncs)

**Comment by pjenvey** [comment] 2020-01-07 20:34
This seems to be a duplicate of #376. The underlying application-services code fails w/ the same "Not all records were successfully uploaded" message, indicating the failure was during a POST that succeeded yet there were bsos that "failed".

**Comment by rfk** [comment] 2020-01-11 00:25
> This seems to be a duplicate of #376. 

I agree, this seems likely. It's probably trying to upload a tombstone record and triggering the same "unknown field `collection`" error.

**Comment by tublitzed** [comment] 2020-02-04 22:21
Closing as dupe of [376](https://github.com/mozilla-services/syncstorage-rs/issues/376)

**Closed by tublitzed** 2020-02-04 22:21 UTC
Labels: bug
