### ISSUE TITLE
Prevent Firefox iOS < 20.0 from crashing when pointed to Durable Sync

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#293] opened 2019-10-18 21:50 UTC
# The problem

We found when testing against staging during the week of 10/14 that Durable Sync completely crashes iOS. We did some digging and found it to be a result of how GCP handles HTTP/2 headers. Fixing this causes iOS not to crash (although at the moment Sync still does not work).

We plan to move forward enabling for new users after determining that number of new users on ff-ios < 20.0 (version with fix) is [~20 or so](https://analytics.amplitude.com/mozilla-corp/chart/s4v6w5o). However, we need to keep this open in order to make sure we address for existing sync users on legacy iOS versions prior to migrating existing users.

# Possible Solutions

Current favorite is to adjust server logic to return error code preventing sync from crashing browser (but causing it to still fail) and then [message users to upgrade](https://github.com/mozilla-mobile/firefox-ios/issues/6294).
[Documented here](https://docs.google.com/spreadsheets/d/1nq8b7ZTLK6XVz5QYZ33EHHmbtYQrNzqSejIQxOVPDa8/edit#gid=0)

#### Requirements:

- [User-Agent string for iOS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox#Firefox_for_iOS) versions we want to identify

  - [Format](https://github.com/mozilla-mobile/firefox-ios/blob/v19.x/Shared/UserAgent.swift#L12): `Firefox-iOS-Sync/<appVersion>b<buildNumber> (<deviceModel>; iPhone OS <systemVersion>) (<app displayName>)`. E.g. `Firefox-iOS-Sync/18.0b1 (iPhone; iPhone OS 13.2.2) (Fennec (synctesting))`
- An appropriate error code/payload to return

## Related links:
[Fix for firefox-ios](https://github.com/mozilla-mobile/firefox-ios/pull/5620)
[Related Sync crashing issue](https://github.com/mozilla-services/syncstorage-rs/issues/277)
[Support case with GCP](https://console.cloud.google.com/support/cases/detail/20994801?organizationId=442341870013&caseId=20994801&accountId=gcp-sa-1256631965)

**Comment by jrconlin** [comment] 2019-10-19 00:10
Is this for iOS? Are we sure that this is because of HTTP/2 headers?

I feel like we may need to add a bit more detail here.

**Comment by tublitzed** [comment] 2019-10-21 14:16
@jrconlin, yes we need a lot more detail. I'm filing this to track progress as we investigate. AFAIK, @fzzzy confirmed last week that it is indeed the headers issue that's crashing iOS. That's the blocker here; that iOS completely crashes.

Sync not working is one thing (which is also bad), but completely crashing Firefox for iOS is going to be a blocker here.

**Comment by fzzzy** [comment] 2019-10-21 22:09
From the support case with GCP, it looks like this is a solution:

https://cloud.google.com/community/tutorials/nginx-ingress-gke

**Comment by tublitzed** [comment] 2019-10-22 04:05
Thanks @fzzzy! I just filed this [bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1590283) for ops to take a look.

**Comment by fzzzy** [comment] 2019-10-22 17:22
Bob says this arrangement is very undesirable and should only be used as a last resort.

**Comment by tublitzed** [comment] 2019-11-01 20:59
Downgrading the severity of this one, and sticking into the TODO list for when we [migrate existing users](https://github.com/mozilla-services/services-eng-issues/issues/6).

**Comment by jchaupitre** [comment] 2020-03-09 19:24
Alex shared [FxA: Firefox iOS WAU by version >20 or <20](https://analytics.amplitude.com/mozilla-corp/chart/ns1zcy4)

**Comment by tublitzed** [comment] 2020-03-12 13:45
Since it's been awhile since this issue cropped up, I want to test one more time that it's actually still a problem before we dedicate time to solving this one.

Testing locally against the last tagged release prior to 20.x which is [17.3](https://github.com/mozilla-mobile/firefox-ios/releases/tag/17.3). Looks like we did have other releases between 17.x and 20.x but they weren't tagged.

17.x requires Swift 5.0.1 which in turn requires XCode 10.2.1 which I found [here](https://developer.apple.com/download/more/) and am downloading now.

I'll build locally and test using my personal FxA account since I know that one is routed to Spanner. Will add notes here as to what I find.

**Comment by tublitzed** [comment] 2020-03-13 13:13
And...it looks like I can't actually build this locally because my version of MacOS is too new to install the required Xcode 10.2.1 dev tools. 😢

**Comment by tublitzed** [comment] 2020-03-13 13:21
Just found this [19.x](https://github.com/mozilla-mobile/firefox-ios/tree/v19.x) branch poking around the ios repo. Going to try that now just in case. 🤞

**Comment by tublitzed** [comment] 2020-03-16 13:42
Ok, it looks like this will need to get some official QA testing. My machine is not old enough to test legacy builds :(. Luckily, it sounds like the QA team has access to older ios builds, which is good news. To be clear, here's what we need specifically:

1. Clarify what happens to the browser when attempting to sync using Firefox-ios 19.x while pointed at Durable Sync. Ie:

* Does the sync succeed?
* Does anything happen with the browser that's unexpected during this time?

@rbillings I'm going to re-assign this one to you to coordinate QA testing with your team. Once that's done, feel free to re-assign this one back over to me with the results linked/etc.

**Comment by tublitzed** [comment] 2020-03-16 16:52
Related PI request: https://jira.mozilla.com/browse/PI-536

**Comment by tublitzed** [comment] 2020-03-19 15:05
It's also worth noting that [this chart today](https://analytics.amplitude.com/mozilla-corp/chart/ns1zcy4) indicates that we're down to ~3.6% of users on FF iOS < 20.0

**Comment by tublitzed** [comment] 2020-03-20 13:24
Confirmed. It's [still an issue](https://jira.mozilla.com/browse/PI-536).

**Comment by pjenvey** [comment] 2020-04-07 23:17
Some kind of 5xx would be best here, we'll opt for returning a 503 here because:

- The nginix frontend converts most 5xx responses to 503s anyway
- iOS handles 503s similar to other 5xxes (giving up and not retrying for another AFAICT 15 minutes)

Despite returning a 503, a `Retry-After` header is not applicable here as the client won't be able to read it due to the case insensitivity issue.

**Closed** 2020-04-08 23:47 UTC
Labels: 5, p1
