### ISSUE TITLE
Sentry not always reporting UA data correctly

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/syncstorage-rs#1027] opened 2021-03-18 22:36 UTC
https://sentry.prod.mozaws.net/operations/syncstorage-prod/issues/10887875/events/62323500/

reports:
![image](https://user-images.githubusercontent.com/35755/111706322-535dd280-87ff-11eb-85bc-77d320783279.png)

with a UA of:
![image](https://user-images.githubusercontent.com/35755/111706368-6670a280-87ff-11eb-8aec-0cfe1998b057.png)

We should ensure that these UAs are being parsed correctly.

(sample UAs can be found at: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox and https://docs.google.com/spreadsheets/d/1I--o6uYWUkBw05IP964Ee2aZCf67P9E3TxpuDawH4_I/edit#gid=0)

**Comment by pjenvey** [comment] 2021-03-18 22:40
It's surprising that any a typical ua parser such as woothee has any success for us. Most if not all of our browsers send a unique User-Agent string to syncstorage! We may need to catalog all the potential ones and formulate our own parser.

**Comment by jrconlin** [comment] 2021-03-18 22:43
Agreed, but it would still be useful to have a catalog of known formats. I'd hope that elements would be reasonably common.

Plus I think we have a long standing issue to generate our own parser for this crap, just for this sort of reason.

**Comment by jrconlin** [comment] 2021-03-18 23:12
To @pjenvey's point, we probably want to scrape the sentry logs for the custom UAs that sync is sending, e.g.

* Firefox/{version} ({platform} {arch) FxSync/{version}.desktop
* Firefox AndroidSync {version} (Firefox)
* Firefox-iOS-Sync/{version} ({arch}; iPhone OS {version|) (Firefox)

**Comment by pjenvey** [comment] 2021-03-23 21:00
I believe one of either the load balancer/nginx logs also has UAs to scrape

**Comment by pjenvey** [comment] 2021-05-05 23:11
Closing this as a duplicate of #788

**Closed by pjenvey** 2021-05-05 23:11 UTC
